# Generated by Django 5.2.7 on 2026-03-12 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kapacitet', models.FloatField(default=5000)),
            ],
        ),
        migrations.CreateModel(
            name='TransakcijaGoriva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drzava', models.CharField(choices=[('bih', 'BiH'), ('rh', 'RH')], max_length=10)),
                ('kolicina', models.FloatField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('napomena', models.CharField(blank=True, max_length=200)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transakcije', to='gorivo.tank')),
            ],
        ),
    ]
