# Generated by Django 5.2.7 on 2026-03-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='bih_gorivo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tank',
            name='rh_gorivo',
            field=models.FloatField(default=0),
        ),
    ]
