# Generated by Django 5.2.7 on 2026-03-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorivo', '0002_tank_bih_gorivo_tank_rh_gorivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='bih_gorivo',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='rh_gorivo',
        ),
        migrations.AddField(
            model_name='transakcijagoriva',
            name='tip',
            field=models.CharField(choices=[('refill', 'Punjenje'), ('potrosnja', 'Potrošnja')], default='Punjenje', max_length=20),
        ),
        migrations.AlterField(
            model_name='transakcijagoriva',
            name='drzava',
            field=models.CharField(blank=True, choices=[('bih', 'BiH'), ('rh', 'RH')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transakcijagoriva',
            name='napomena',
            field=models.TextField(blank=True),
        ),
    ]
