# Generated by Django 5.2.7 on 2026-03-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorivo', '0003_remove_tank_bih_gorivo_remove_tank_rh_gorivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transakcijagoriva',
            name='drzava',
            field=models.CharField(blank=True, choices=[('bih', 'BiH'), ('rh', 'RH')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='transakcijagoriva',
            name='napomena',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transakcijagoriva',
            name='tip',
            field=models.CharField(choices=[('refill', 'Punjenje'), ('potrosnja', 'Potrošnja')], max_length=20),
        ),
    ]
