# Generated by Django 5.2.7 on 2026-03-12 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorivo', '0004_alter_transakcijagoriva_drzava_and_more'),
        ('ture', '0027_alter_radninalog_ostali_troskovi'),
    ]

    operations = [
        migrations.AddField(
            model_name='transakcijagoriva',
            name='vozilo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tocenja', to='ture.vozilo'),
        ),
    ]
