# Generated by Django 5.2.7 on 2025-11-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacija', models.CharField(max_length=255)),
                ('datum_polaska', models.DateField()),
                ('datum_dolaska', models.DateField()),
                ('kilometraza', models.PositiveIntegerField()),
                ('zaduz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razduz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razlika', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('broj_putnog_naloga', models.CharField(max_length=50)),
                ('iznos_ture', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dnevnice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cekanje', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
