# Generated by Django 5.2.7 on 2025-11-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tura',
            name='broj_putnog_naloga',
        ),
        migrations.AddField(
            model_name='tura',
            name='br_putnog_naloga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tura',
            name='cekanje',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tura',
            name='dnevnice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tura',
            name='iznos_ture',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tura',
            name='kilometraza',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tura',
            name='razduz',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tura',
            name='razlika',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tura',
            name='zaduz',
            field=models.FloatField(),
        ),
    ]
