# Generated by Django 5.2.7 on 2025-11-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0002_remove_tura_broj_putnog_naloga_tura_br_putnog_naloga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tura',
            name='dnevnice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
