# Generated by Django 5.2.7 on 2025-11-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0003_alter_tura_dnevnice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tura',
            old_name='br_putnog_naloga',
            new_name='broj_putnog_naloga',
        ),
        migrations.RenameField(
            model_name='tura',
            old_name='razduz',
            new_name='razduzenje',
        ),
        migrations.RenameField(
            model_name='tura',
            old_name='zaduz',
            new_name='zaduzenje',
        ),
    ]
