# Generated by Django 5.2.7 on 2025-11-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0004_rename_br_putnog_naloga_tura_broj_putnog_naloga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tura',
            name='zaduzenje_prethodni_mjesec',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
