# Generated by Django 5.2.7 on 2025-11-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0005_tura_zaduzenje_prethodni_mjesec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tura',
            name='zaduzenje_prethodni_mjesec',
        ),
    ]
