# Generated by Django 5.2.7 on 2025-11-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0007_tura_zaduzenje_prethodni_mjesec'),
    ]

    operations = [
        migrations.AddField(
            model_name='tura',
            name='na_banku',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
