# Generated by Django 5.2.7 on 2025-11-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0008_tura_na_banku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tura',
            name='na_banku',
        ),
        migrations.RemoveField(
            model_name='tura',
            name='zaduzenje_prethodni_mjesec',
        ),
    ]
