# Generated by Django 5.2.7 on 2025-11-05 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0009_remove_tura_na_banku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vozac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('zaduzenje_prethodni_mjesec', models.FloatField(default=0)),
                ('uplaceno_na_banku', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='tura',
            name='vozac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ture', to='ture.vozac'),
        ),
    ]
