# Generated by Django 5.2.7 on 2025-11-05 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0010_vozac_tura_vozac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tura',
            name='vozac',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ture', to='ture.vozac'),
            preserve_default=False,
        ),
    ]
