# Generated by Django 5.2.7 on 2025-11-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0011_alter_tura_vozac'),
    ]

    operations = [
        migrations.AddField(
            model_name='vozac',
            name='postotak',
            field=models.FloatField(default=0),
        ),
    ]
