# Generated by Django 5.2.7 on 2025-11-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0012_vozac_postotak'),
    ]

    operations = [
        migrations.AddField(
            model_name='tura',
            name='aktivan',
            field=models.BooleanField(default=True),
        ),
    ]
