# Generated by Django 5.2.7 on 2025-11-07 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0013_tura_aktivan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vozilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('vrijeme_registracije', models.DateField()),
                ('servis', models.DateField()),
                ('dodatne_informacije', models.TextField(blank=True, null=True)),
                ('vozac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vozila', to='ture.vozac')),
            ],
        ),
    ]
