# Generated by Django 5.2.7 on 2025-11-07 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0014_vozilo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naputak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadrzaj', models.TextField(verbose_name='Sadržaj naputka')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('vozilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naputci', to='ture.vozilo')),
            ],
            options={
                'ordering': ['-datum'],
            },
        ),
    ]
