# Generated by Django 5.2.7 on 2025-11-14 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0015_naputak'),
    ]

    operations = [
        migrations.AddField(
            model_name='tura',
            name='granica_polazak',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tura',
            name='granica_povratak',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tura',
            name='datum_dolaska',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tura',
            name='datum_polaska',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tura',
            name='iznos_ture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tura',
            name='kilometraza',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tura',
            name='razduzenje',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RadniNalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konacna_drzava', models.CharField(choices=[('BiH', 'BiH'), ('Austrija', 'Austrija'), ('Njemacka', 'Njemacka'), ('Slovenija', 'Slovenija'), ('Francuska', 'Francuska'), ('Hrvatska', 'Hrvatska'), ('Madjarska', 'Madjarska'), ('Svicarska', 'Svicarska'), ('Italija', 'Italija')], max_length=50)),
                ('tuzemne_dnevnice', models.FloatField(blank=True, null=True)),
                ('inozemne_dnevnice', models.FloatField(blank=True, null=True)),
                ('tura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='radni_nalog', to='ture.tura')),
            ],
        ),
    ]
