# Generated by Django 5.2.7 on 2025-11-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0016_tura_granica_polazak_tura_granica_povratak_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CijenaDnevnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drzava', models.CharField(choices=[('BiH', 'BiH'), ('Austrija', 'Austrija'), ('Njemacka', 'Njemacka'), ('Slovenija', 'Slovenija'), ('Francuska', 'Francuska'), ('Hrvatska', 'Hrvatska'), ('Madjarska', 'Madjarska'), ('Svicarska', 'Svicarska'), ('Italija', 'Italija')], max_length=50, unique=True)),
                ('iznos', models.FloatField(help_text='Iznos dnevnica u EUR po danu')),
            ],
            options={
                'verbose_name_plural': 'Cijene dnevnica',
            },
        ),
    ]
