# Generated by Django 5.2.7 on 2025-11-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0018_populate_cijene_dnevnica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cijenadnevnica',
            name='drzava',
            field=models.CharField(choices=[('BiH', 'BiH'), ('Austrija', 'Austrija'), ('Njemacka', 'Njemačka'), ('Slovenija', 'Slovenija'), ('Francuska', 'Francuska'), ('Hrvatska', 'Hrvatska'), ('Madjarska', 'Mađarska'), ('Svicarska', 'Švicarska'), ('Italija', 'Italija')], max_length=50, unique=True),
        ),
    ]
