# Generated by Django 5.2.7 on 2025-11-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0019_alter_cijenadnevnica_drzava'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radninalog',
            name='konacna_drzava',
            field=models.CharField(choices=[('BiH', 'BiH'), ('Austrija', 'Austrija'), ('Njemačka', 'Njemačka'), ('Slovenija', 'Slovenija'), ('Francuska', 'Francuska'), ('Hrvatska', 'Hrvatska'), ('Mađarska', 'Mađarska'), ('Švicarska', 'Švicarska'), ('Italija', 'Italija')], max_length=50),
        ),
    ]
