# Generated by Django 5.2.7 on 2025-11-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0020_alter_radninalog_konacna_drzava'),
    ]

    operations = [
        migrations.AddField(
            model_name='radninalog',
            name='aktivan',
            field=models.BooleanField(default=True),
        ),
    ]
