# Generated by Django 5.2.7 on 2025-12-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0021_radninalog_aktivan'),
    ]

    operations = [
        migrations.AddField(
            model_name='vozilo',
            name='bazdar_tahografa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vozilo',
            name='periodicni_pregled',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vozilo',
            name='pozarni_aparati',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vozilo',
            name='tu_potvrda',
            field=models.DateField(blank=True, null=True),
        ),
    ]
