# Generated by Django 5.2.7 on 2026-02-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0022_vozilo_bazdar_tahografa_vozilo_periodicni_pregled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vozac',
            name='valuta',
            field=models.CharField(choices=[('KM', 'KM'), ('EUR', 'EUR')], default='KM', max_length=3),
        ),
    ]
