# Generated by Django 5.2.7 on 2026-02-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0023_vozac_valuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='radninalog',
            name='cestarine',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radninalog',
            name='ostali_troskovi',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radninalog',
            name='papiri',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radninalog',
            name='terminali',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
