# Generated by Django 5.2.7 on 2026-02-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0024_radninalog_cestarine_radninalog_ostali_troskovi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radninalog',
            name='cestarine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radninalog',
            name='ostali_troskovi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radninalog',
            name='papiri',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radninalog',
            name='terminali',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
