# Generated by Django 5.2.7 on 2026-02-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0025_alter_radninalog_cestarine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radninalog',
            name='izdaci',
            field=models.TextField(blank=True, null=True),
        ),
    ]
