# Generated by Django 5.2.7 on 2026-02-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0026_radninalog_izdaci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radninalog',
            name='ostali_troskovi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
